receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680

processors:
#  authentication:
  splitbatch:

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - splitbatch
      exporters:
        - logging
